version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8888:8000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
    networks:
      - net-backend
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 6001:5432
    env_file:
      - ./.env
    restart: always
    networks:
      - net-backend
  cache:
    image: redis:latest
    depends_on:
      - web
      - db
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - net-backend

volumes:
  postgres_data:
  cache:
    driver: local

networks:
  net-backend:
